"""Read-only completed fixed12 step0 audit; never run a model or optimizer.

Default mode additionally replays the three CPU draw manifests under pinned
torch2.10. --metadata-only checks hashes, all trace inputs/targets, reported
statistics and scope without importing torch; it is not a passed draw replay.
Prediction errors and parameter-mutation claims are checked for consistency
with saved sufficient statistics/hashes, not regenerated by a model forward.
"""
from __future__ import annotations

import argparse
from collections import Counter
from dataclasses import asdict
import hashlib
import json
import math
from pathlib import Path
import re
import statistics
import time

import numpy as np

from pi05_libero_world_model_adapter import LiberoFeaturePack, LiberoWindowDataset, sha256_file


ROOT = Path(__file__).resolve().parents[1]
RESULT = "simulation_output/pi05_libero_action_study_step0_v1"
PACK = "simulation_output/pi05_libero_action_study_features_v1"
PLAN = "docs/libero-action-study-step0-plan-v1.json"
PLAN_SHA = "2716481652a40b783b55eaec4cd7ec54f6e7de845f0a249d54355b6ffedd21c9"
REPORT_SHA = "1075355fc7ca0a519e40438aa6554cbf6fb3ec476b8be96c3abc8a9e480f3248"
SEEDS = (20260912, 20260913, 20260914)
ARMS = ("observed_action", "normalized_zero_action")
NAMES = (*ARMS, "persistence")
COUNTS = {"train": 1086, "validation": 500}


def require(value, message):
    if not value:
        raise ValueError(message)


def canonical(value):
    return json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":"), allow_nan=False)


def parse(text):
    def pairs(items):
        result = {}
        for key, value in items:
            require(key not in result, "duplicate JSON key")
            result[key] = value
        return result
    def reject(value):
        raise ValueError(f"nonfinite JSON value: {value}")
    return json.loads(text, object_pairs_hook=pairs, parse_constant=reject)


def read(path):
    return parse(path.read_text(encoding="utf-8"))


def lines(path):
    with path.open(encoding="utf-8") as stream:
        return [parse(line) for line in stream]


def digest(value):
    require(type(value) is str and re.fullmatch("[0-9a-f]{64}", value), "lowercase SHA256 required")
    return value


def checked(root, name, expected):
    require(type(name) is str and name and "\\" not in name and ":" not in name
            and not Path(name).is_absolute() and all(p not in ("", ".", "..") for p in name.split("/")), "safe relative path required")
    path = (root / name).resolve()
    require(path.is_relative_to(root.resolve()) and path.is_file(), f"missing/escaped file: {name}")
    require(sha256_file(path) == digest(expected), f"hash differs: {name}")
    return path


def close_number(actual, expected, label):
    if expected is None:
        require(actual is None, f"unsupported metric differs: {label}")
    else:
        require(type(actual) in (int, float) and math.isfinite(actual)
                and math.isclose(actual, expected, rel_tol=1e-10, abs_tol=1e-10), f"number differs: {label}")


def array_hash(value):
    value = np.ascontiguousarray(value)
    require(value.dtype in (np.dtype("float32"), np.dtype("bool")), "only ordinary native float32/bool arrays")
    dtype = "torch.bool" if value.dtype == np.bool_ else "torch.float32"
    return hashlib.sha256(canonical({"shape": list(value.shape), "dtype": dtype}).encode()
                          + value.tobytes()).hexdigest()


def batch_fingerprints(items, section):
    result = {}
    for key in items[0][section]:
        values = [item[section][key] for item in items]
        result[key] = canonical(values) if key == "task_instruction" else array_hash(np.stack(values))
    return result


def check_stats(node):
    if isinstance(node, list):
        for value in node:
            check_stats(value)
    elif isinstance(node, dict):
        if "count" in node:
            count = node["count"]
            require(type(count) is int and count >= 0, "invalid sufficient-stat count")
            absolute, squared = node["absolute_error_sum"], node["squared_error_sum"]
            require(all(type(x) in (int, float) and math.isfinite(x) and x >= 0 for x in (absolute, squared)), "invalid error sums")
            require(count > 0 or absolute == squared == 0, "unsupported metric has nonzero error sum")
            close_number(node["mae"], absolute / count if count else None, "MAE from sufficient sums")
            close_number(node["rmse"], math.sqrt(squared / count) if count else None, "RMSE from sufficient sums")
        else:
            for value in node.values():
                check_stats(value)


def merged_stats(micro, episodes):
    """Micro sufficient sums/counts must equal pooled per-episode sums/counts."""
    if isinstance(micro, list):
        require(all(isinstance(row, list) and len(row) == len(micro) for row in episodes), "metric axis mismatch")
        for index, value in enumerate(micro):
            merged_stats(value, [row[index] for row in episodes])
    else:
        require(isinstance(micro, dict) and all(isinstance(row, dict) and set(row) == set(micro) for row in episodes), "metric tree mismatch")
        if "count" in micro:
            require(micro["count"] == sum(row["count"] for row in episodes), "micro count is not sum of episodes")
            for key in ("absolute_error_sum", "squared_error_sum"):
                close_number(micro[key], math.fsum(row[key] for row in episodes), "micro pooled " + key)
        else:
            for key, value in micro.items():
                merged_stats(value, [row[key] for row in episodes])


def check_summary(summary, windows, batches, stats):
    require(summary["window_count"] == windows and summary["update_count"] == batches
            and summary["horizon"] == 3 and summary["visual_dim"] == 2048
            and summary["state_std"] == stats["state_std"], "summary coverage/layout/std differs")
    for key in ("visual", "state_normalized", "state_native"):
        check_stats(summary[key])
    visual, state, native = summary["visual"], summary["state_normalized"], summary["state_native"]
    require(visual["aggregate"]["count"] == windows*3*2*2048
            and state["aggregate"]["count"] == windows*3*8, "aggregate target support differs")
    for row in visual["per_horizon"]:
        require(row["count"] == windows*2*2048, "visual horizon support differs")
    for row in visual["per_view"]:
        require(row["count"] == windows*3*2048, "visual view support differs")
    for row in state["per_horizon"]:
        require(row["count"] == windows*8, "state horizon support differs")
    for key in ("state_normalized", "state_native"):
        for row in summary[key]["per_coordinate"]:
            require(row["count"] == windows*3, "state coordinate support differs")
        for horizon in summary[key]["per_horizon_coordinate"]:
            for row in horizon:
                require(row["count"] == windows, "state horizon-coordinate support differs")
    for horizon in visual["per_horizon_view"]:
        for row in horizon:
            require(row["count"] == windows*2048, "visual horizon-view support differs")
    for group, width in (("position", 3), ("axis_angle_coordinates", 3), ("gripper", 2)):
        require(native["groups"][group]["count"] == windows*3*width, "native same-unit group support differs")
    loss = summary["masked_objective"]
    require(loss["visual_count"] == windows*3*2*2048 and loss["state_count"] == windows*3*8, "objective support differs")
    for branch in ("visual", "state"):
        require(math.isfinite(loss[branch+"_sum"]) and loss[branch+"_sum"] >= 0, "invalid objective sum")
        close_number(loss[branch+"_loss"], loss[branch+"_sum"]/loss[branch+"_count"], "objective branch mean")
    close_number(loss["total"], loss["visual_loss"] + .25*loss["state_loss"], "objective total")


def scalars(summary):
    return {"normalized_state_mae": summary["state_normalized"]["aggregate"]["mae"],
            "normalized_state_rmse": summary["state_normalized"]["aggregate"]["rmse"],
            "visual_mae": summary["visual"]["aggregate"]["mae"],
            "visual_rmse": summary["visual"]["aggregate"]["rmse"],
            "masked_objective": summary["masked_objective"]["total"]}


def check_changes(actual, candidate, reference):
    require(set(actual) == set(candidate) == set(reference), "comparison metric keys differ")
    for key, value in candidate.items():
        ref = reference[key]
        delta = value-ref if value is not None and ref is not None else None
        close_number(actual[key]["absolute"], delta, "absolute change")
        close_number(actual[key]["relative_percent"], 100*delta/ref if delta is not None and ref else None, "relative change")


def audit(root=ROOT, report_sha256=REPORT_SHA, *, replay=True):
    started = time.monotonic()
    root = Path(root).resolve()
    require(report_sha256 == REPORT_SHA, "only the completed fixed step0 report is allowed")
    report = read(checked(root, RESULT + "/report.json", report_sha256))
    plan = read(checked(root, PLAN, PLAN_SHA))
    require(report["plan_sha256"] == PLAN_SHA and report["status"] == "passed_fixed_draws_paired_random_step0_only", "wrong completed result/plan")
    status = read(root / RESULT / "status.json")
    require(status == {"status": "completed", "report_sha256": REPORT_SHA, "optimizer_steps": 0}, "not completed")
    for name, expected in report["input_sha256"].items():
        checked(root, name, expected)
    require(all(report["input_sha256"].get(k) == v for k, v in plan["input_sha256"].items()), "result/plan input pins differ")
    for name, expected in report["output_sha256"].items():
        checked(root, RESULT + "/" + name, expected)
    files = {p.relative_to(root / RESULT).as_posix() for p in (root / RESULT).rglob("*") if p.is_file()}
    require(files == set(report["output_sha256"]) | {"report.json", "status.json"}, "unexpected/missing result output")
    for key in ("optimizer_steps", "backward_calls", "feature_extractions", "policy_actions", "simulation_steps"):
        require(type(report[key]) is int and report[key] == 0, "zero-step scope changed: " + key)
    for key in ("optimizer_constructed", "training_started", "trained_checkpoint_written", "family_independence_verified",
                "training_ready", "formal_data_allowed", "real_system_validated"):
        require(report[key] is False, "scope flag changed: " + key)
    require(report["input_files_unchanged"] is True and report["checkpoint_training_overlap_unknown"] is True, "provenance boundary differs")
    require(report["runtime"] == {"torch": "2.10.0+cu128", "device": "cpu", "dtype": "float32", "threads": 1,
            "deterministic_algorithms": True, "amp": False, "tf32": False, "cuda_initialized": False}, "recorded runtime differs")
    if replay:
        import torch
        require(str(torch.__version__) == "2.10.0+cu128", "full replay requires pinned remote torch2.10; metadata-only does not replay draws")
        from pi05_libero_action_study_sampling import verify_draw_manifest
    trace = lines(root / RESULT / "evaluation_trace.jsonl")
    require(len(trace) == 312, "exactly312 step0 batches required")
    trace_index = {}
    for item in trace:
        key = (str(item["seed"]), item["partition"], tuple(item["window_indices"]))
        require(key not in trace_index, "duplicate trace batch")
        trace_index[key] = item
    require(set(report["runs"]) == set(map(str, SEEDS)) and set(report["sampling"]) == set(map(str, SEEDS)), "fixed three seeds required")
    trace_batches_checked = 0
    predictions_not_regenerated = 0
    initial_hashes, primary, replayed = set(), {}, 0
    sampling_index = read(root / RESULT / "sampling_index.json")
    with LiberoFeaturePack(root / PACK) as pack:
        split = pack.load_split(root / PACK / "split.json")
        require({k: split[k] for k in plan["selected_split"]} == plan["selected_split"], "fixed split differs")
        stats = read(root / PACK / "preparation/normalization.json")
        datasets = {p: LiberoWindowDataset(pack, split, partition=p, normalization=stats) for p in COUNTS}
        train_windows = lines(root / PACK / "preparation/train_windows.jsonl")
        require(canonical(train_windows) == canonical([asdict(w) for w in datasets["train"].windows]), "saved train windows differ")
        groups = {}
        for eid in split["train_episode_indices"]:
            groups.setdefault(pack.episodes[eid]["leakage_group_id"], []).append(eid)
        require(sampling_index["groups"] == groups and sampling_index["seeds"] == report["sampling"]
                and sampling_index["prospective_batches_per_seed"] == 200 and sampling_index["batch_size"] == 16
                and sampling_index["execution_authorized"] is False
                and sampling_index["normalization_sha256"] == sha256_file(root / PACK / "preparation/normalization.json"), "sampling index differs")
        batch_cache = {}
        for part, dataset in datasets.items():
            require(len(dataset) == COUNTS[part], "fixed window count differs")
            ids = {}
            for i, window in enumerate(dataset.windows):
                ids.setdefault(window.episode_index, []).append(i)
            batches = []
            for eid, indices in ids.items():
                for start in range(0, len(indices), 16):
                    selected = indices[start:start+16]
                    items = [dataset[i] for i in selected]
                    actions = np.stack([x["inputs"]["candidate_actions"] for x in items])
                    anchor = np.stack([x["inputs"]["history_visual_latent"][-1] for x in items])
                    persistence = {"pred_future_visual_latent": array_hash(np.broadcast_to(anchor[:, None, None], (len(items), 1, 3, 2, 2048))),
                                   "pred_state_delta": array_hash(np.zeros((len(items), 1, 3, 8), dtype=np.float32))}
                    batches.append({"eid": eid, "indices": selected, "inputs": batch_fingerprints(items, "inputs"),
                                    "targets": batch_fingerprints(items, "targets"), "zero": array_hash(np.zeros_like(actions)),
                                    "action_changes": int((actions != 0).sum()), "persistence": persistence})
            batch_cache[part] = (ids, batches)
        for seed in SEEDS:
            entry = report["sampling"][str(seed)]
            require(entry == {"path": f"draws_seed{seed}.json", "sha256": report["output_sha256"][f"draws_seed{seed}.json"],
                    "draw_count": 3200, "both_arms_reference_this_same_file": True, "optimizer_updates_executed": 0}, "shared draw entry differs")
            manifest = read(root / RESULT / entry["path"])
            require(manifest["seed"] == seed and manifest["draw_count"] == 3200 and manifest["batches"] == 200
                    and manifest["batch_size"] == 16 and manifest["shared_arms"] == list(ARMS)
                    and manifest["optimizer_steps"] == 0 and manifest["training_started"] is False, "draw scope/count differs")
            if replay:
                verify_draw_manifest(manifest, train_windows, groups)
                replayed += 1
            require(set(report["runs"][str(seed)]) == set(COUNTS), "both full partitions required")
            seed_hash = None
            for part, (ids, batches) in batch_cache.items():
                run = report["runs"][str(seed)][part]
                require(run["parameters_and_versions_unchanged"] is True and run["only_action_input_changed"] is True
                        and run["common_target_support_shared"] is True and run["optimizer_steps"] == run["backward_calls"] == 0,
                        "paired no-update declaration differs")
                parameter_hashes = run["parameter_sha256"]
                require(set(parameter_hashes) == set(ARMS) and len(set(parameter_hashes.values())) == 1, "paired initial parameter identity differs")
                current_hash = digest(parameter_hashes[ARMS[0]])
                require(seed_hash is None or seed_hash == current_hash, "parameter identity changed between partitions")
                seed_hash = current_hash
                seen = []
                for batch in batches:
                    key = (str(seed), part, tuple(batch["indices"]))
                    require(key in trace_index, "missing planned trace batch")
                    t = trace_index[key]
                    require(t["episode_index"] == batch["eid"], "batch crosses episode")
                    require(t["source_input_sha256"] == batch["inputs"]
                            and t["original_target_sha256"] == t["common_target_sha256"] == batch["targets"], "trace source/target bytes differ from immutable cache")
                    require(set(t["arm_input_sha256"]) == set(ARMS)
                            and t["arm_input_sha256"][ARMS[0]] == batch["inputs"]
                            and t["arm_input_sha256"][ARMS[1]] == {**batch["inputs"], "candidate_actions": batch["zero"]}, "non-action change or nonzero normalized action input")
                    require(set(t["predictions_sha256"]) == set(NAMES)
                            and t["predictions_sha256"]["persistence"] == batch["persistence"], "persistence prediction hash differs")
                    for name in ARMS:
                        require(set(t["predictions_sha256"][name]) == {"pred_future_visual_latent", "pred_state_delta"}, "prediction key boundary differs")
                        for value in t["predictions_sha256"][name].values():
                            digest(value)
                    predictions_not_regenerated += 2
                    trace_batches_checked += 1
                    seen.extend(batch["indices"])
                require(Counter(seen) == Counter(range(COUNTS[part])), "each partition window must occur exactly once")
                require(run["coverage"] == {"windows": COUNTS[part], "batches": len(batches),
                    "action_values_changed": sum(b["action_changes"] for b in batches),
                    "original_state_scalars": COUNTS[part]*3*8, "common_state_scalars": COUNTS[part]*3*8,
                    "original_visual_views": COUNTS[part]*3*2, "common_visual_views": COUNTS[part]*3*2}, "run support/coverage differs")
                require(set(run["arms"]) == set(NAMES), "required results missing")
                for arm in run["arms"].values():
                    episodes = arm["per_episode"]
                    require(set(episodes) == set(map(str, ids)), "episode metrics membership differs")
                    for eid, indices in ids.items():
                        check_summary(episodes[str(eid)], len(indices), math.ceil(len(indices)/16), stats)
                    micro = arm["micro"]
                    check_summary(micro, COUNTS[part], len(batches), stats)
                    for key in ("visual", "state_normalized", "state_native"):
                        merged_stats(micro[key], [e[key] for e in episodes.values()])
                    for key in ("visual_sum", "state_sum", "visual_count", "state_count"):
                        close_number(micro["masked_objective"][key], math.fsum(e["masked_objective"][key] for e in episodes.values()), "micro objective pooled " + key)
                    values = [scalars(e) for e in episodes.values()]
                    require(set(arm["episode_macro"]) == set(values[0]), "macro keys differ")
                    for key in values[0]:
                        close_number(arm["episode_macro"][key], statistics.mean(v[key] for v in values), "equal episode macro " + key)
                macros = {name: run["arms"][name]["episode_macro"] for name in NAMES}
                comparisons = run["episode_macro_changes"]
                require(set(comparisons) == {"observed_minus_zero", *[a+"_minus_persistence" for a in ARMS]}, "comparison keys differ")
                check_changes(comparisons["observed_minus_zero"], macros[ARMS[0]], macros[ARMS[1]])
                for arm in ARMS:
                    check_changes(comparisons[arm+"_minus_persistence"], macros[arm], macros["persistence"])
                if part == "validation":
                    primary[str(seed)] = macros[ARMS[0]]["normalized_state_mae"]-macros[ARMS[1]]["normalized_state_mae"]
            initial_hashes.add(seed_hash)
    require(len(initial_hashes) == 3 and trace_batches_checked == len(trace_index) == 312, "seed diversity or complete trace coverage differs")
    observed = report["validation_random_observed_minus_zero_mae"]
    require(set(observed["by_seed"]) == set(primary), "primary seed coverage differs")
    for seed, value in primary.items():
        close_number(observed["by_seed"][seed], value, "primary paired difference")
    close_number(observed["mean"], statistics.mean(primary.values()), "primary mean")
    close_number(observed["descriptive_population_std"], statistics.pstdev(primary.values()), "descriptive seed std")
    for name, expected in report["input_sha256"].items():
        checked(root, name, expected)
    for name, expected in report["output_sha256"].items():
        checked(root, RESULT + "/" + name, expected)
    checked(root, RESULT + "/report.json", REPORT_SHA)
    checked(root, PLAN, PLAN_SHA)
    return {"schema": "libero_action_study_step0_readback_v1",
            "status": "passed_step0_metadata_trace_statistics_and_draw_replay" if replay else "passed_metadata_trace_statistics_only_draw_replay_not_run",
            "report_sha256": REPORT_SHA, "plan_sha256": PLAN_SHA, "audit_tool_sha256": sha256_file(Path(__file__)),
            "input_files_rehashed": len(report["input_sha256"]), "output_files_rehashed": len(report["output_sha256"]),
            "draw_manifests_replayed": replayed, "prospective_draws": 9600, "trace_batches_checked": trace_batches_checked,
            "per_seed_partition_windows": COUNTS, "source_target_batch_bytes_reconstructed_from_cache": True,
            "persistence_prediction_batch_hashes_recomputed": 312, "paired_prediction_batches_not_regenerated": predictions_not_regenerated,
            "metric_scope": "saved sufficient-stat arithmetic, per-episode macro and pooled micro; model errors not regenerated",
            "parameter_scope": "paired/partition hashes and unchanged declarations checked; no parameter file or forward replay",
            "model_constructed": False, "model_forward_calls": 0, "optimizer_steps": 0, "backward_calls": 0,
            "training_ready": False, "formal_data_allowed": False, "family_independence_verified": False,
            "checkpoint_training_overlap_unknown": True, "learned_action_benefit_evaluated": False,
            "policy_benefit_evaluated": False, "real_system_validated": False,
            "decision": "step0 mechanics only; no trained action-information benefit or causal/robustness/policy claim",
            "runtime_seconds": time.monotonic()-started}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--report-sha256", required=True)
    parser.add_argument("--metadata-only", action="store_true", help="No torch import or draw replay; explicitly partial readback")
    args = parser.parse_args()
    print(json.dumps(audit(report_sha256=args.report_sha256, replay=not args.metadata_only), indent=2, allow_nan=False))


if __name__ == "__main__":
    main()
